[package]
name = "feo-new"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uint = "0.9"
fixed-hash = "0.8"
tiny-keccak = { version = "2.0", features = ["sha3"] }
