//! # Semantic Analyser
//!
//! Responsible for performing semantic analysis on the abstract syntax tree (AST) generated by
//! the parser. This analysis ensures that the code is semantically correct according to
//! the language's rules, checking for issues such as type mismatches, undefined variables
//! and incorrect patterns in the code.

mod expr;
mod patt;
mod symbol_table;

#[cfg(test)]
mod tests;

use crate::{
    ast::{
        AliasDecl, ConstantDecl, EnumDef, EnumVariantStruct, EnumVariantTupleStruct,
        EnumVariantType, Expression, FunctionItem, FunctionOrMethodParam, FunctionParam,
        Identifier, ImportDecl, InherentImplDef, InherentImplItem, Item, Keyword, ModuleItem,
        SelfType, Statement, StaticVarDecl, StructDef, StructDefField, TraitDef, TraitDefItem,
        TraitImplDef, TraitImplItem, TupleStructDef, TupleStructDefField, Type, TypePath, UnitType,
        Visibility,
    },
    error::{CompilerError, SemanticErrorKind},
    logger::{LogLevel, Logger},
    parser::{ty::get_type_paths, Program},
    span::{Span, Spanned},
};

use std::collections::HashMap;

use expr::{analyse_expr, wrap_into_expression};
use symbol_table::{Module, Scope, ScopeKind, Symbol, SymbolTable};

/// Mapping from a `TypePath`` (representing a concrete type) to a vector of `TraitImplDef`
/// (representing implemented traits)
type TypeTable = HashMap<TypePath, Vec<TraitImplDef>>;

/// Struct responsible for performing semantic analysis on the abstract syntax tree (AST)
/// of the program. It manages the scopes, symbol tables, and errors encountered during
/// the analysis phase.
#[allow(dead_code)]
struct SemanticAnalyser {
    scope_stack: Vec<Scope>,
    lib_registry: HashMap<Identifier, Vec<Module>>,
    errors: Vec<CompilerError<SemanticErrorKind>>,
    logger: Logger,
    type_table: TypeTable,
}

#[allow(dead_code)]
impl SemanticAnalyser {
    /// Construct a new `SemanticAnalyser` instance. Initialize the logger, external symbols
    /// and module registry. Add any external code (e.g., library functions) to the global scope
    /// if provided.
    pub(crate) fn new(
        log_level: LogLevel,
        external_code: Option<HashMap<Identifier, Vec<Module>>>,
    ) -> Self {
        let mut logger = Logger::new(log_level);
        let mut symbols: SymbolTable = HashMap::new();
        let mut lib_registry: HashMap<Identifier, Vec<Module>> = HashMap::new();

        if let Some(code) = external_code {
            logger.debug(&format!(
                "external code detected – importing code from {:?}",
                code.keys()
            ));

            for (name, modules) in code {
                for module in modules.iter() {
                    for (path, sym) in module.table.iter() {
                        symbols.insert(path.clone(), sym.clone());
                    }
                }

                lib_registry.insert(name, modules);

                // TODO: if the symbol is a trait implementation, also update the `TypeTable` to add
                // TODO: trait implementations for a given implementing type (replace the current
                // TODO: empty `HashMap`)
            }
        }

        let public_scope = Scope {
            scope_kind: ScopeKind::Public,
            symbols,
        };

        logger.trace("entering public scope …");

        SemanticAnalyser {
            scope_stack: vec![public_scope],
            lib_registry,
            errors: Vec::new(),
            logger,
            type_table: HashMap::new(),
        }
    }

    /// Push a new scope onto the scope stack and log the action.
    fn enter_scope(&mut self, scope_kind: ScopeKind) {
        self.logger
            .debug(&format!("entering new scope: `{scope_kind:?}` …"));

        self.scope_stack.push(Scope {
            scope_kind,
            symbols: HashMap::new(),
        });
    }

    /// Pop the top scope from the scope stack and log the action.
    fn exit_scope(&mut self) -> Option<Scope> {
        if let Some(exited_scope) = self.scope_stack.pop() {
            self.logger
                .debug(&format!("exited scope: `{:?}`", exited_scope.scope_kind));

            Some(exited_scope)
        } else {
            None
        }
    }

    /// Insert a symbol into the current scope's symbol table.
    fn insert(&mut self, path: TypePath, symbol: Symbol) -> Result<(), SemanticErrorKind> {
        if let Some(curr_scope) = self.scope_stack.last_mut() {
            self.logger.debug(&format!(
                "inserting symbol `{symbol}` into scope `{:?}` at path `{path}` …",
                curr_scope.scope_kind
            ));

            curr_scope.symbols.insert(path.clone(), symbol.clone());

            if let Some(modules) = self.lib_registry.get_mut(&Identifier::from("lib")) {
                for module in modules.iter_mut() {
                    if module.name == path.type_name {
                        module.table.insert(path.clone(), symbol.clone());
                    }
                }
            }

            Ok(())
        } else {
            Err(SemanticErrorKind::UndefinedScope)
        }
    }

    /// Look up a symbol by its path in the current scope stack, starting from the innermost scope,
    /// and log the lookup result.
    fn lookup(&mut self, path: &TypePath) -> Option<&Symbol> {
        for scope in self.scope_stack.iter().rev() {
            if let Some(symbol) = scope.symbols.get(path) {
                self.logger.debug(&format!(
                    "found symbol `{symbol}` in scope `{:?}` at path `{path}`",
                    scope.scope_kind
                ));

                return Some(symbol);
            } else {
                for (sym_path, symbol) in scope.symbols.iter() {
                    if path.type_name == sym_path.type_name {
                        self.logger.debug(&format!(
                            "found symbol `{symbol}` in scope `{:?}` at path `{path}`",
                            scope.scope_kind
                        ));

                        return Some(&symbol);
                    }
                }
            }
        }

        self.logger
            .warn(&format!("path `{path:?}` not found in current scope"));

        None
    }

    /// Initiate semantic analysis on the provided program. This involves analysing all statements
    /// within the program, checking for type mismatches and validating symbol definitions.
    fn analyse_program(
        &mut self,
        program: &Program,
    ) -> Result<(), Vec<CompilerError<SemanticErrorKind>>> {
        self.logger.debug(&format!("starting semantic analysis …"));

        self.enter_scope(ScopeKind::ProgramRoot);

        self.lib_registry
            .insert(Identifier::from("lib"), Vec::new());

        for stmt in &program.statements {
            self.analyse_stmt(stmt, TypePath::from(Identifier::from("")))
                .map_err(|_| self.errors.clone())?
        }

        if !self.errors.is_empty() {
            return Err(self.errors.clone());
        }

        self.logger
            .info("semantic analysis complete, no errors detected");

        Ok(())
    }

    // TODO: alphabetize match arms
    // TODO: add custom errors to specify context when unifying types
    // TODO: (e.g., function args / struct fields)

    /// Analyse individual statements within the program, determining their validity and handling
    /// specific types of statements, such as variable declarations, item definitions and expressions.
    /// Check for semantic correctness and ensures that the statement adheres to the expected types
    /// and scope rules.
    fn analyse_stmt(
        &mut self,
        statement: &Statement,
        root: TypePath,
    ) -> Result<(), SemanticErrorKind> {
        match statement {
            Statement::Let(ls) => {
                self.logger
                    .trace(&format!("analysing let statement: `{statement}`"));

                // variables declared must have a type and are assigned the unit type if not;
                // this prevents uninitialized variable errors
                let mut value_type = if let Some(val) = &ls.value_opt {
                    analyse_expr(self, val, &root)?
                } else {
                    Type::UnitType(UnitType)
                };

                // get the type annotation if there is one, otherwise assume the value's type
                let declared_type = match &ls.type_ann_opt {
                    Some(ty) => ty.clone(),
                    _ => value_type.clone(),
                };

                let mut symbol_table = if let Some(scope) = self.scope_stack.last() {
                    scope.symbols.to_owned()
                } else {
                    HashMap::new()
                };

                self.unify_types(&mut symbol_table, &declared_type, &mut value_type)?;

                // check that the value matches the type annotation
                if &value_type != &declared_type {
                    return Err(SemanticErrorKind::TypeMismatchDeclaredType {
                        actual_type: value_type,
                        declared_type,
                    });
                }

                let assignee_path = ls.assignee.name.to_type_path();

                let symbol = match &value_type {
                    Type::I32(_)
                    | Type::I64(_)
                    | Type::U8(_)
                    | Type::U16(_)
                    | Type::U32(_)
                    | Type::U64(_)
                    | Type::U256(_)
                    | Type::U512(_)
                    | Type::F32(_)
                    | Type::F64(_)
                    | Type::Byte(_)
                    | Type::B2(_)
                    | Type::B4(_)
                    | Type::B8(_)
                    | Type::B16(_)
                    | Type::B32(_)
                    | Type::H160(_)
                    | Type::H256(_)
                    | Type::H512(_)
                    | Type::Str(_)
                    | Type::Char(_)
                    | Type::Bool(_)
                    | Type::UnitType(_)
                    | Type::GroupedType(_)
                    | Type::Array { .. }
                    | Type::Tuple(_)
                    | Type::FunctionPtr(_)
                    | Type::Reference { .. }
                    | Type::SelfType(_)
                    | Type::InferredType(_)
                    | Type::Vec { .. }
                    | Type::Mapping { .. }
                    | Type::Option { .. }
                    | Type::Result { .. } => Symbol::Variable {
                        name: ls.assignee.name.clone(),
                        var_type: value_type,
                    },
                    Type::UserDefined(tp) => match self.lookup(&tp) {
                        Some(sym) => sym.clone(),
                        _ => Symbol::Variable {
                            name: ls.assignee.name.clone(),
                            var_type: value_type,
                        },
                    },
                    Type::Generic { name, bound_opt } => Symbol::Variable {
                        name: name.clone(),
                        var_type: Type::UserDefined(
                            bound_opt
                                .clone()
                                .unwrap_or(TypePath::from(Identifier::from("_"))),
                        ),
                    },
                };

                // add the variable to the symbol table
                self.insert(assignee_path, symbol)?;
            }

            Statement::Item(item) => match item {
                Item::ImportDecl(id) => {
                    self.logger
                        .trace(&format!("analysing import declaration: `{statement}`"));

                    match self.analyse_import(id, &root.type_name) {
                        Ok(_) => (),
                        Err(err) => self.log_error(err, &id.span),
                    }
                }

                Item::AliasDecl(ad) => {
                    self.logger
                        .trace(&format!("analysing alias declaration: `{statement}`"));

                    let alias_path = root.join(ad.alias_name.to_type_path());

                    self.insert(
                        alias_path.clone(),
                        Symbol::Alias {
                            path: alias_path,
                            visibility: ad.visibility.clone(),
                            alias_name: ad.alias_name.clone(),
                            original_type_opt: ad.original_type_opt.clone(),
                        },
                    )?;
                }

                Item::ConstantDecl(cd) => {
                    self.logger
                        .trace(&format!("analysing constant declaration: `{statement}`"));

                    let value_type = match &cd.value_opt {
                        Some(val) => {
                            let value = wrap_into_expression(val.clone());
                            Some(analyse_expr(self, &value, &root)?)
                        }
                        _ => None,
                    };

                    let mut symbol_table = if let Some(scope) = self.scope_stack.last() {
                        scope.symbols.to_owned()
                    } else {
                        HashMap::new()
                    };

                    self.unify_types(
                        &mut symbol_table,
                        &cd.constant_type,
                        &mut value_type.clone().unwrap_or(Type::inferred_type("_")),
                    )?;

                    if value_type.clone().is_some_and(|t| t != *cd.constant_type) {
                        return Err(SemanticErrorKind::TypeMismatchDeclaredType {
                            declared_type: *cd.constant_type.clone(),
                            actual_type: value_type.unwrap(),
                        });
                    }

                    let constant_path = root.join(cd.constant_name.to_type_path());

                    self.insert(
                        constant_path.clone(),
                        Symbol::Constant {
                            path: constant_path,
                            visibility: cd.visibility.clone(),
                            constant_name: cd.constant_name.clone(),
                            constant_type: value_type.unwrap_or(Type::inferred_type("_")),
                        },
                    )?;
                }

                Item::StaticVarDecl(s) => {
                    self.logger.trace(&format!(
                        "analysing static variable declaration: `{statement}`"
                    ));

                    let mut assignee_type = match &s.assignee_opt {
                        Some(a_expr) => {
                            let assignee = wrap_into_expression(*a_expr.clone());
                            analyse_expr(self, &assignee, &root)?
                        }
                        _ => Type::inferred_type("_"),
                    };

                    let mut symbol_table = if let Some(scope) = self.scope_stack.last() {
                        scope.symbols.to_owned()
                    } else {
                        HashMap::new()
                    };

                    self.unify_types(&mut symbol_table, &s.var_type, &mut assignee_type)?;

                    if &assignee_type != &s.var_type {
                        return Err(SemanticErrorKind::TypeMismatchDeclaredType {
                            declared_type: s.var_type.clone(),
                            actual_type: assignee_type,
                        });
                    }

                    let static_var_path = root.join(s.var_name.to_type_path());

                    self.insert(
                        static_var_path,
                        Symbol::Variable {
                            name: s.var_name.clone(),
                            var_type: s.var_type.clone(),
                        },
                    )?;
                }

                Item::ModuleItem(m) => {
                    // TODO: sort out visibility

                    let mut module_errors: Vec<SemanticErrorKind> = Vec::new();

                    let module_path = root.join(m.module_name.to_type_path());

                    self.logger
                        .trace(&format!("analysing module item: `{module_path}` …"));

                    let scope_kind = ScopeKind::Module(module_path.clone());

                    let mut module_scope = Scope {
                        scope_kind: scope_kind.clone(),
                        symbols: HashMap::new(),
                    };

                    self.enter_scope(scope_kind);

                    if let Some(items) = &m.items_opt {
                        for item in items.iter() {
                            match self.analyse_stmt(
                                &Statement::Item(item.clone()),
                                m.module_name.to_type_path(),
                            ) {
                                Ok(_) => (),
                                Err(err) => {
                                    self.log_error(err.clone(), &item.span());
                                    module_errors.push(err)
                                }
                            }
                        }
                    }

                    if !module_errors.is_empty() {
                        return Err(SemanticErrorKind::ModuleErrors {
                            name: m.module_name.clone(),
                        });
                    }

                    if let Some(curr_scope) = self.scope_stack.pop() {
                        self.logger
                            .trace(&format!("exiting scope: `{:?}`", curr_scope.scope_kind));

                        module_scope = curr_scope;
                    }

                    self.insert(
                        module_path.clone(),
                        Symbol::Module {
                            path: module_path.clone(),
                            module: m.clone(),
                            symbols: module_scope.symbols.clone(),
                        },
                    )?;

                    self.logger.trace(&format!(
                        "inserting symbols into module at path: `{module_path}` …",
                    ));

                    if let Some(modules) = self.lib_registry.get_mut(&Identifier::from("lib")) {
                        self.logger.trace(&format!(
                            "inserting module `{}` into library registry under local library …",
                            m.module_name
                        ));

                        let module = Module {
                            name: m.module_name.clone(),
                            table: module_scope.symbols,
                        };

                        modules.push(module);
                    }
                }

                Item::TraitDef(t) => {
                    let trait_name_path = t.trait_name.to_type_path();
                    let trait_def_path = root.join(trait_name_path.clone());

                    self.logger
                        .trace(&format!("analysing trait definition: `{trait_def_path}` …",));

                    self.insert(
                        trait_def_path.clone(),
                        Symbol::Trait {
                            path: trait_name_path.clone(),
                            trait_def: t.clone(),
                        },
                    )?;

                    // TODO: insert optional generics into scope if they are not already

                    if let Some(items) = &t.trait_items_opt {
                        // self.enter_scope(ScopeKind::TraitDef(trait_def_path.to_string()));

                        for i in items.iter() {
                            match i {
                                TraitDefItem::AliasDecl(ad) => {
                                    self.analyse_stmt(
                                        &Statement::Item(Item::AliasDecl(ad.clone())),
                                        trait_def_path.clone(),
                                    )?;
                                }
                                TraitDefItem::ConstantDecl(cd) => self.analyse_stmt(
                                    &Statement::Item(Item::ConstantDecl(cd.clone())),
                                    trait_def_path.clone(),
                                )?,
                                TraitDefItem::FunctionItem(fi) => {
                                    let function_name_path = fi.function_name.to_type_path();

                                    let function_def_path =
                                        trait_def_path.join(function_name_path.clone());

                                    self.insert(
                                        function_def_path,
                                        Symbol::Function {
                                            path: function_name_path,
                                            function: fi.clone(),
                                        },
                                    )?;

                                    match self.analyse_function_def(
                                        fi,
                                        &trait_def_path,
                                        true,
                                        false,
                                    ) {
                                        Ok(_) => (),
                                        Err(err) => self.log_error(err, &t.span),
                                    }
                                }
                            }
                        }
                    }
                }

                Item::EnumDef(e) => {
                    let enum_name_path = e.enum_name.to_type_path();
                    let enum_def_path = root.join(enum_name_path.clone());

                    self.logger
                        .trace(&format!("analysing enum definition: `{enum_def_path}` …"));

                    self.insert(
                        enum_def_path.clone(),
                        Symbol::Enum {
                            path: enum_name_path,
                            enum_def: e.clone(),
                        },
                    )?;

                    // TODO: insert optional generics into scope if they are not already

                    for variant in e.variants.clone() {
                        let variant_path = enum_def_path.join(variant.variant_name.to_type_path());

                        if let Some(variant_type) = variant.variant_type_opt {
                            match variant_type {
                                EnumVariantType::Struct(s) => {
                                    self.insert(
                                        variant_path.clone(),
                                        Symbol::Struct {
                                            path: variant_path,
                                            struct_def: StructDef {
                                                attributes_opt: None,
                                                visibility: Visibility::Private,
                                                kw_struct: Keyword::Anonymous,
                                                struct_name: variant.variant_name,
                                                generic_params_opt: None,
                                                fields_opt: Some(s.struct_fields),
                                                span: Span::default(),
                                            },
                                        },
                                    )?;
                                }
                                EnumVariantType::TupleStruct(t) => {
                                    self.insert(
                                        variant_path.clone(),
                                        Symbol::TupleStruct {
                                            path: variant_path.clone(),
                                            tuple_struct_def: TupleStructDef {
                                                attributes_opt: None,
                                                visibility: Visibility::Private,
                                                kw_struct: Keyword::Anonymous,
                                                struct_name: variant_path.to_identifier(),
                                                generic_params_opt: None,
                                                fields_opt: {
                                                    let mut elements: Vec<TupleStructDefField> =
                                                        Vec::new();

                                                    for elem_type in t.element_types {
                                                        let elem = TupleStructDefField {
                                                            attributes_opt: None,
                                                            visibility: Visibility::Private,
                                                            field_type: Box::new(elem_type),
                                                        };

                                                        elements.push(elem);
                                                    }

                                                    Some(elements)
                                                },
                                                span: Span::default(),
                                            },
                                        },
                                    )?;
                                }
                            }
                        } else {
                            self.insert(
                                variant_path.clone(),
                                Symbol::Variable {
                                    name: variant_path.to_identifier(),
                                    var_type: Type::UserDefined(variant_path),
                                },
                            )?;
                        }
                    }
                }

                Item::StructDef(s) => {
                    let struct_name_path = s.struct_name.to_type_path();
                    let struct_def_path = root.join(struct_name_path.clone());

                    self.logger.trace(&format!(
                        "analysing struct definition: `{struct_def_path}` …"
                    ));

                    self.insert(
                        struct_def_path,
                        Symbol::Struct {
                            path: struct_name_path,
                            struct_def: s.clone(),
                        },
                    )?;

                    // TODO: insert optional generics into scope if they are not already
                }

                Item::TupleStructDef(ts) => {
                    let struct_name_path = ts.struct_name.to_type_path();
                    let tuple_struct_path = root.join(struct_name_path.clone());

                    self.logger.trace(&format!(
                        "analysing tuple struct definition: `{tuple_struct_path}` …"
                    ));

                    self.insert(
                        tuple_struct_path,
                        Symbol::TupleStruct {
                            path: struct_name_path,
                            tuple_struct_def: ts.clone(),
                        },
                    )?;

                    // TODO: insert optional generics into scope if they are not already
                }

                Item::InherentImplDef(iid) => {
                    let type_path = root.join(iid.nominal_type.clone());

                    self.logger.trace(&format!(
                        "analysing inherent implementation for type: `{type_path}` …",
                    ));

                    if let Some(items) = &iid.associated_items_opt {
                        // self.enter_scope(ScopeKind::Impl(type_path.to_string()));

                        for i in items.iter() {
                            match i {
                                InherentImplItem::ConstantDecl(cd) => self.analyse_stmt(
                                    &Statement::Item(Item::ConstantDecl(cd.clone())),
                                    type_path.clone(),
                                )?,
                                InherentImplItem::FunctionItem(fi) => {
                                    let function_name_path = fi.function_name.to_type_path();

                                    let function_def_path =
                                        type_path.join(function_name_path.clone());

                                    self.insert(
                                        function_def_path.clone(),
                                        Symbol::Function {
                                            path: function_name_path,
                                            function: fi.clone(),
                                        },
                                    )?;

                                    match self.analyse_function_def(fi, &type_path, true, false) {
                                        Ok(_) => (),
                                        Err(err) => self.log_error(err, &iid.span),
                                    }
                                }
                            }
                        }

                        // self.exit_scope();
                    }
                }

                Item::TraitImplDef(t) => {
                    let trait_impl_path = match &t.implementing_type {
                        Type::UserDefined(tp) => root
                            .join(tp.clone())
                            .join(t.implemented_trait_path.type_name.to_type_path()),

                        ty => {
                            return Err(SemanticErrorKind::UnexpectedType {
                                expected: "user-defined type".to_string(),
                                found: ty.clone(),
                            })
                        }
                    };

                    self.logger.trace(&format!(
                        "analysing trait `{}` implementation for type `{}` …",
                        t.implemented_trait_path, t.implementing_type
                    ));

                    self.add_trait_implementation(trait_impl_path.clone(), t.clone());

                    if let Some(items) = &t.associated_items_opt {
                        // self.enter_scope(ScopeKind::TraitImpl(trait_impl_path.to_string()));

                        for i in items.iter() {
                            match i {
                                TraitImplItem::AliasDecl(ad) => self.analyse_stmt(
                                    &Statement::Item(Item::AliasDecl(ad.clone())),
                                    trait_impl_path.clone(),
                                )?,
                                TraitImplItem::ConstantDecl(cd) => self.analyse_stmt(
                                    &Statement::Item(Item::ConstantDecl(cd.clone())),
                                    trait_impl_path.clone(),
                                )?,
                                TraitImplItem::FunctionItem(fi) => {
                                    let function_impl_path =
                                        trait_impl_path.join(fi.function_name.to_type_path());

                                    self.insert(
                                        function_impl_path.clone(),
                                        Symbol::Function {
                                            path: function_impl_path,
                                            function: fi.clone(),
                                        },
                                    )?;

                                    match self.analyse_function_def(
                                        fi,
                                        &trait_impl_path,
                                        true,
                                        true,
                                    ) {
                                        Ok(_) => (),
                                        Err(err) => self.log_error(err, &t.span),
                                    }
                                }
                            }
                        }
                    }
                }

                Item::FunctionItem(f) => {
                    let function_name_path = f.function_name.to_type_path();
                    let function_item_path = root.join(function_name_path.clone());

                    self.logger.trace(&format!(
                        "analysing function item: `{function_item_path}({:?}) -> {}`",
                        f.params_opt.clone().unwrap_or(Vec::new()),
                        f.return_type_opt
                            .clone()
                            .unwrap_or(Box::new(Type::UnitType(UnitType)))
                    ));

                    self.insert(
                        function_item_path,
                        Symbol::Function {
                            path: function_name_path,
                            function: f.clone(),
                        },
                    )?;

                    // TODO: insert optional generics into scope if they are not already

                    match self.analyse_function_def(f, &root, false, false) {
                        Ok(_) => (),
                        Err(err) => {
                            self.log_error(err, &f.span);
                        }
                    }
                }
            },

            Statement::Expression(expr) => {
                self.logger
                    .trace(&format!("analysing expression statement: `{statement}`"));

                match analyse_expr(self, expr, &root) {
                    Ok(_) => (),
                    Err(e) => self.log_error(e, &expr.span()),
                }
            }
        }

        Ok(())
    }

    /// Analyse a function definition within a specific context, including its parameters,
    /// body, and return type.
    fn analyse_function_def(
        &mut self,
        f: &FunctionItem,
        path: &TypePath,
        is_associated_func: bool,
        is_trait_impl: bool,
    ) -> Result<(), SemanticErrorKind> {
        // What is the root path? [i.e., path to the function, excluding the function name]
        // Options:
        // * module (e.g., `lib::some_module` or just `lib`)
        // * object implementation (e.g., `lib::some_module::SomeObject`)
        // * trait implementation (e.g., `lib::some_module::SomeObject::SomeTrait`)

        let function_root = if is_trait_impl {
            if let Some(prefix) = &path.associated_type_path_prefix_opt {
                TypePath::from(prefix.clone())
            } else {
                path.clone()
            }
        } else {
            path.clone()
        };

        // append the function name to the root
        let full_path = function_root.join(f.function_name.to_type_path());

        self.enter_scope(ScopeKind::Function(full_path.clone()));

        // register generic parameters in the local scope
        if let Some(generic_params) = &f.generic_params_opt {
            for generic_param in &generic_params.params {
                self.insert(
                    generic_param.name.to_type_path(),
                    Symbol::Variable {
                        name: generic_param.name.clone(),
                        var_type: Type::Generic {
                            name: generic_param.name.clone(),
                            bound_opt: generic_param.type_bound_opt.clone(),
                        },
                    },
                )?;
            }
        }

        if let Some(params) = &f.params_opt {
            let param_types: Vec<Type> = params.iter().map(|p| p.param_type()).collect();

            for (param, mut param_type) in params.iter().zip(param_types) {
                if param_type == Type::SelfType(SelfType) {
                    if is_associated_func {
                        param_type = Type::UserDefined(function_root.clone());
                    }
                }

                let param_path = param.param_name().to_type_path();

                match param_type {
                    Type::Generic { name, .. } => match self.lookup(&name.to_type_path()) {
                        Some(_) => (),
                        None => {
                            return Err(SemanticErrorKind::UndeclaredGenericParams {
                                found: format!("`{name}`"),
                            })
                        }
                    },

                    Type::FunctionPtr(fp) => {
                        self.insert(
                            param_path.clone(),
                            Symbol::Function {
                                path: param_path.clone(),
                                function: FunctionItem {
                                    attributes_opt: None,
                                    visibility: Visibility::Private,
                                    kw_func: Keyword::Anonymous,
                                    function_name: Identifier::from(""),
                                    generic_params_opt: None,
                                    params_opt: fp.params_opt,
                                    return_type_opt: fp.return_type_opt,
                                    block_opt: None,
                                    span: Span::default(),
                                },
                            },
                        )?;
                    }

                    Type::UserDefined(tp) => match self.lookup(&tp).cloned() {
                        Some(sym) => self.insert(param_path, sym.clone())?,
                        None => {
                            return Err(SemanticErrorKind::UndefinedType { name: tp.type_name });
                        }
                    },

                    ty => self.insert(
                        param_path,
                        Symbol::Variable {
                            name: param.param_name(),
                            var_type: ty,
                        },
                    )?,
                }
            }
        }

        let mut function_type = if let Some(block) = &f.block_opt {
            // split path into a vector to remove the last element (if needed), then convert back
            let mut path_vec = Vec::<Identifier>::from(path.clone());

            if is_associated_func {
                path_vec.pop(); // remove associated type name
            }

            self.logger
                .trace(&format!("analysing body of function `{full_path}()` …"));

            analyse_expr(
                self,
                &Expression::Block(block.clone()),
                &TypePath::from(path_vec),
            )?
        } else {
            if let Some(ty) = &f.return_type_opt {
                *ty.clone()
            } else {
                Type::UnitType(UnitType)
            }
        };

        // check that the function type matches the return type
        if let Some(return_type) = &f.return_type_opt {
            let mut symbol_table = if let Some(scope) = self.scope_stack.last() {
                scope.symbols.to_owned()
            } else {
                HashMap::new()
            };

            self.unify_types(&mut symbol_table, &return_type, &mut function_type)?;
        }

        self.logger.trace(&format!(
            "analysed function: `{full_path}() -> {}`",
            f.return_type_opt
                .clone()
                .unwrap_or(Box::new(Type::UnitType(UnitType)))
        ));

        self.exit_scope();

        Ok(())
    }

    /// Analyse an import declaration, resolving and inserting symbols from the imported
    /// modules into the current scope.
    fn analyse_import(
        &mut self,
        import_decl: &ImportDecl,
        lib_root: &Identifier,
    ) -> Result<(), SemanticErrorKind> {
        let path_segments = import_decl.import_tree.path_segments.clone();

        let import_paths = get_type_paths(path_segments);

        for import_path in import_paths.iter() {
            let import_root =
                if let Some(ids) = import_path.associated_type_path_prefix_opt.as_ref() {
                    if !ids.is_empty() {
                        ids.first().cloned().unwrap()
                    } else {
                        import_path.type_name.clone()
                    }
                } else {
                    lib_root.clone()
                };

            // bring external libraries into scope
            if let Some(modules) = self.lib_registry.get(&import_root).cloned() {
                self.logger.debug(&format!(
                    "detected library `{import_root:?}` in library registry"
                ));

                for module in modules.iter() {
                    for (item_path, symbol) in module.table.iter() {
                        if let Some(scope) = self.scope_stack.last().cloned() {
                            if let Symbol::Module { symbols, .. } = symbol {
                                for (path, sym) in symbols {
                                    if !scope.symbols.contains_key(&import_path) {
                                        self.insert(path.clone(), sym.clone())?;
                                    } else if !scope
                                        .symbols
                                        .contains_key(&import_path.type_name.to_type_path())
                                    {
                                        self.insert(path.type_name.to_type_path(), symbol.clone())?;
                                    }
                                }
                            } else {
                                if !scope.symbols.contains_key(&import_path) {
                                    self.insert(item_path.clone(), symbol.clone())?;
                                } else if !scope
                                    .symbols
                                    .contains_key(&import_path.type_name.to_type_path())
                                {
                                    self.insert(
                                        item_path.type_name.to_type_path(),
                                        symbol.clone(),
                                    )?;
                                }
                            }
                        }
                    }
                }
            } else {
                return Err(SemanticErrorKind::UndefinedLibrary { name: import_root });
            }
        }

        Ok(())
    }

    /// Analyse a function or method call expression by resolving the provided path, validating
    /// arguments and determining the return type.
    fn analyse_call_or_method_call_expr(
        &mut self,
        path: TypePath,
        args_opt: Option<Vec<Expression>>,
    ) -> Result<Type, SemanticErrorKind> {
        match self.lookup(&path).cloned() {
            Some(Symbol::Function { function, .. }) => {
                let func_params = function.params_opt.clone();
                let func_def_return_type = function.return_type_opt.clone();

                match (&args_opt, &func_params) {
                    (None, None) => match func_def_return_type {
                        Some(ty) => Ok(*ty),
                        _ => Ok(Type::UnitType(UnitType)),
                    },
                    (None, Some(params)) => {
                        let mut self_counter: usize = 0;
                        let mut func_param_counter: usize = 0;

                        for param in params {
                            if let Type::SelfType(_) = param.param_type() {
                                self_counter += 1;
                            } else {
                                func_param_counter += 1;
                            }
                        }

                        if self_counter > 1 {
                            return Err(SemanticErrorKind::MethodParamCountError);
                        }

                        if self_counter != params.len() {
                            return Err(SemanticErrorKind::FuncArgCountMismatch {
                                function_path: path.to_identifier(),
                                expected: self_counter,
                                found: self_counter + func_param_counter,
                            });
                        }

                        match func_def_return_type {
                            Some(ty) => Ok(*ty),
                            _ => Ok(Type::UnitType(UnitType)),
                        }
                    }
                    (Some(args), None) => Err(SemanticErrorKind::FuncArgCountMismatch {
                        function_path: path.to_identifier(),
                        expected: 0,
                        found: args.len(),
                    }),
                    (Some(args), Some(params)) => {
                        let mut self_counter: usize = 0;

                        for param in params {
                            if let Type::SelfType(_) = param.param_type() {
                                self_counter += 1;
                            }
                        }

                        if self_counter > 1 {
                            return Err(SemanticErrorKind::MethodParamCountError);
                        }

                        let num_func_params = params.len() - self_counter;

                        if args.len() != num_func_params {
                            return Err(SemanticErrorKind::FuncArgCountMismatch {
                                function_path: path.to_identifier(),
                                expected: params.len(),
                                found: args.len(),
                            });
                        }

                        for (arg, param) in args.iter().zip(params) {
                            let mut arg_type = analyse_expr(self, &arg, &path)?;

                            let param_type = param.param_type();

                            let mut symbol_table = if let Some(scope) = self.scope_stack.last() {
                                scope.symbols.to_owned()
                            } else {
                                HashMap::new()
                            };

                            self.unify_types(&mut symbol_table, &param_type, &mut arg_type)?;

                            if arg_type != param_type {
                                return Err(SemanticErrorKind::TypeMismatchArg {
                                    arg_id: function.function_name.clone(),
                                    expected: param_type,
                                    found: arg_type,
                                });
                            }
                        }

                        match func_def_return_type {
                            Some(ty) => Ok(*ty),
                            None => Ok(Type::UnitType(UnitType)),
                        }
                    }
                }
            }

            None => Err(SemanticErrorKind::UndefinedFunc {
                name: path.type_name,
            }),
            Some(sym) => Err(SemanticErrorKind::UnexpectedSymbol {
                name: path.type_name,
                expected: "function".to_string(),
                found: format!("`{sym}`"),
            }),
        }
    }

    /// Unifies two types, ensuring they are compatible. Returns `Ok` if they can be unified, or
    /// an `Err` if there is a type mismatch.
    fn unify_types(
        &mut self,
        symbol_table: &mut SymbolTable,
        type_a: &Type,
        type_b: &mut Type,
    ) -> Result<(), SemanticErrorKind> {
        let type_a_clone = type_a.clone();
        let type_b_clone = type_b.clone();

        self.logger.trace(&format!(
            "unifying types `{type_a_clone}` and `{type_b_clone}`"
        ));

        match (type_a_clone, type_b_clone) {
            // if both types are the same, they are already unified
            _ if type_a == type_b => Ok(()),

            (Type::InferredType(_), _) => Err(SemanticErrorKind::UnexpectedInferredType),

            // TODO: custom error
            (Type::SelfType(_), _) => Err(SemanticErrorKind::UnexpectedType {
                expected: "non-`Self` type".to_string(),
                found: Type::SelfType(SelfType),
            }),

            (Type::UserDefined(_), Type::SelfType(_)) => {
                unify_self_type(type_b, type_a.clone());
                Ok(())
            }

            (ty, Type::SelfType(_)) => Err(SemanticErrorKind::UnexpectedType {
                expected: "user-defined type".to_string(),
                found: ty,
            }),

            // if one is a concrete or generic type and the other is inferred, resolve the inference
            (concrete_or_generic, Type::InferredType(_)) => {
                unify_inferred_type(type_b, concrete_or_generic);
                Ok(())
            }

            (
                Type::Generic {
                    name: name_a,
                    bound_opt: bound_a,
                },
                Type::Generic {
                    name: name_b,
                    bound_opt: bound_b,
                },
            ) => {
                if name_a == name_b {
                    match (bound_a, bound_b) {
                        (None, None) => (),
                        (None, Some(_)) => {
                            return Err(SemanticErrorKind::TypeBoundCountMismatch {
                                expected: 0,
                                found: 1,
                            })
                        }
                        (Some(_), None) => {
                            return Err(SemanticErrorKind::TypeBoundCountMismatch {
                                expected: 1,
                                found: 0,
                            })
                        }
                        (Some(a), Some(b)) => {
                            if a != b {
                                return Err(SemanticErrorKind::TypeMismatchTypeBound {
                                    expected: a.to_identifier(),
                                    found: b.to_identifier(),
                                });
                            }
                        }
                    }

                    Ok(())
                } else {
                    Err(SemanticErrorKind::TypeMismatchUnification {
                        expected: Identifier::from(&type_a.to_string()),
                        found: Identifier::from(&type_b.to_string()),
                    })
                }
            }

            // TODO: custom error
            (Type::Generic { name, bound_opt }, _) => {
                return Err(SemanticErrorKind::UnexpectedType {
                    expected: "non-generic type".to_string(),
                    found: Type::Generic { name, bound_opt },
                });
            }

            (concrete, Type::Generic { .. }) => {
                self.unify_generic_with_concrete(symbol_table, type_b, &concrete)
            }

            (Type::GroupedType(grouped), matched) => {
                if *grouped != matched {
                    return Err(SemanticErrorKind::TypeMismatchInnerType {
                        context: "grouped".to_string(),
                        expected: format!("`{grouped}`"),
                        found: matched,
                    });
                }

                Ok(())
            }

            (
                Type::Array {
                    element_type: elem_type_a,
                    num_elements: num_elems_a,
                },
                Type::Array {
                    element_type: elem_type_b,
                    num_elements: num_elems_b,
                },
            ) => {
                if elem_type_a != elem_type_b {
                    return Err(SemanticErrorKind::TypeMismatchArrayElems {
                        expected: format!("`{elem_type_a}`"),
                        found: *elem_type_b,
                    });
                }

                if num_elems_a != num_elems_b {
                    return Err(SemanticErrorKind::ArrayLengthMismatch {
                        expected: num_elems_a.into(),
                        found: num_elems_b.into(),
                    });
                }

                Ok(())
            }

            (Type::Tuple(elem_types_a), Type::Tuple(elem_types_b)) => {
                if elem_types_a.len() != elem_types_b.len() {
                    return Err(SemanticErrorKind::TupleLengthMismatch {
                        expected: elem_types_a.len(),
                        found: elem_types_b.len(),
                    });
                }

                for (a, b) in elem_types_a.into_iter().zip(elem_types_b) {
                    if a != b {
                        return Err(SemanticErrorKind::TypeMismatchTupleElems {
                            expected: a,
                            found: b,
                        });
                    }
                }

                Ok(())
            }

            (Type::FunctionPtr(ptr_a), Type::FunctionPtr(ptr_b)) => {
                match (&ptr_a.params_opt, ptr_b.params_opt) {
                    (None, None) => (),
                    (None, Some(params_b)) => {
                        return Err(SemanticErrorKind::ParamCountMismatch {
                            expected: 0,
                            found: params_b.len(),
                        })
                    }
                    (Some(params_a), None) => {
                        return Err(SemanticErrorKind::ParamCountMismatch {
                            expected: params_a.len(),
                            found: 0,
                        })
                    }
                    (Some(params_a), Some(params_b)) => {
                        if params_a.len() != params_b.len() {
                            return Err(SemanticErrorKind::ParamCountMismatch {
                                expected: params_a.len(),
                                found: params_b.len(),
                            });
                        }

                        for (param_a, param_b) in params_a.iter().zip(params_b) {
                            match (param_a, param_b) {
                                (
                                    FunctionOrMethodParam::FunctionParam(func_param_a),
                                    FunctionOrMethodParam::FunctionParam(func_param_b),
                                ) => {
                                    if *func_param_a != func_param_b {
                                        return Err(SemanticErrorKind::TypeMismatchParam {
                                            expected: *func_param_a.param_type.clone(),
                                            found: *func_param_b.param_type,
                                        });
                                    }
                                }
                                (
                                    FunctionOrMethodParam::FunctionParam(param_a),
                                    FunctionOrMethodParam::MethodParam(param_b),
                                ) => {
                                    return Err(SemanticErrorKind::UnexpectedParam {
                                        expected: format!("`{}`", param_a.param_type),
                                        found: Identifier::from(&param_b.kw_self.to_string()),
                                    })
                                }
                                (
                                    FunctionOrMethodParam::MethodParam(param_a),
                                    FunctionOrMethodParam::FunctionParam(param_b),
                                ) => {
                                    return Err(SemanticErrorKind::UnexpectedParam {
                                        expected: format!("`{}`", param_a.kw_self),
                                        found: Identifier::from(&format!("{}", param_b.param_type)),
                                    })
                                }
                                (
                                    FunctionOrMethodParam::MethodParam(self_param_a),
                                    FunctionOrMethodParam::MethodParam(self_param_b),
                                ) => {
                                    match (
                                        &self_param_a.reference_op_opt,
                                        &self_param_b.reference_op_opt,
                                    ) {
                                        (None, None) => (),
                                        (None, Some(_)) | (Some(_), None) => {
                                            return Err(SemanticErrorKind::TypeMismatchSelfParam {
                                                expected: format!("`{self_param_a}`"),
                                                found: format!("`{self_param_b}`"),
                                            });
                                        }
                                        (Some(ref_op_a), Some(ref_op_b)) => {
                                            if ref_op_a != ref_op_b {
                                                return Err(
                                                    SemanticErrorKind::TypeMismatchSelfParam {
                                                        expected: format!("`{self_param_a}`"),
                                                        found: format!("`{self_param_b}`"),
                                                    },
                                                );
                                            }
                                        }
                                    }

                                    match (self_param_a.kw_self, self_param_b.kw_self) {
                                        (Keyword::SelfKeyword, Keyword::SelfKeyword) => (),
                                        (_, kw) => {
                                            return Err(SemanticErrorKind::UnexpectedKeyword {
                                                expected: Keyword::SelfKeyword.to_string(),
                                                found: kw,
                                            });
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                match (ptr_a.return_type_opt, ptr_b.return_type_opt) {
                    (None, None) => (),
                    (None, Some(ty)) => {
                        if let Type::UnitType(UnitType) = *ty {
                            ()
                        } else {
                            return Err(SemanticErrorKind::UnexpectedReturnType { found: *ty });
                        }
                    }
                    (Some(ty), None) => {
                        if let Type::UnitType(UnitType) = *ty {
                            ()
                        } else {
                            return Err(SemanticErrorKind::MissingReturnType { expected: *ty });
                        }
                    }
                    (Some(return_type_a), Some(return_type_b)) => {
                        if return_type_a != return_type_b {
                            return Err(SemanticErrorKind::TypeMismatchReturnType {
                                expected: *return_type_a,
                                found: *return_type_b,
                            });
                        }
                    }
                }

                Ok(())
            }

            (
                Type::Reference {
                    reference_op: ref_op_a,
                    inner_type: inner_type_a,
                },
                Type::Reference {
                    reference_op: ref_op_b,
                    inner_type: inner_type_b,
                },
            ) => {
                if ref_op_a != ref_op_b {
                    return Err(SemanticErrorKind::RefOperatorMismatch {
                        expected: ref_op_a,
                        found: ref_op_b,
                    });
                }

                if inner_type_a != inner_type_b {
                    return Err(SemanticErrorKind::TypeMismatchInnerType {
                        context: "reference".to_string(),
                        expected: format!("`{ref_op_a}{inner_type_a}`"),
                        found: *inner_type_b,
                    });
                }

                Ok(())
            }

            (
                Type::Vec {
                    element_type: elem_type_a,
                },
                Type::Vec {
                    element_type: elem_type_b,
                },
            ) => {
                if elem_type_a != elem_type_b {
                    return Err(SemanticErrorKind::TypeMismatchArrayElems {
                        expected: format!("`{elem_type_a}`"),
                        found: *elem_type_b,
                    });
                }

                Ok(())
            }

            (
                Type::Mapping {
                    key_type: key_type_a,
                    value_type: val_type_a,
                },
                Type::Mapping {
                    key_type: key_type_b,
                    value_type: val_type_b,
                },
            ) => {
                if key_type_a != key_type_b {
                    return Err(SemanticErrorKind::TypeMismatchMappingKey {
                        expected: *key_type_a,
                        found: *key_type_b,
                    });
                }

                if val_type_a != val_type_b {
                    return Err(SemanticErrorKind::TypeMismatchMappingValue {
                        expected: *val_type_a,
                        found: *val_type_b,
                    });
                }

                Ok(())
            }

            (
                Type::Option {
                    inner_type: inner_type_a,
                },
                Type::Option {
                    inner_type: inner_type_b,
                },
            ) => {
                if inner_type_a != inner_type_b {
                    return Err(SemanticErrorKind::TypeMismatchInnerType {
                        context: "`Some` variant in `Option<T>`".to_string(),
                        expected: format!("`{inner_type_a}`"),
                        found: *inner_type_b,
                    });
                }

                Ok(())
            }

            (Type::Result { .. }, Type::Result { .. }) => unify_result_types(type_b, &type_a),

            (Type::UserDefined(type_path_a), Type::UserDefined(type_path_b)) => {
                if type_path_a != type_path_b {
                    return Err(SemanticErrorKind::TypeMismatchUserDefined {
                        expected: type_path_a.to_identifier(),
                        found: type_path_b.to_identifier(),
                    });
                }

                Ok(())
            }

            _ => Err(SemanticErrorKind::TypeMismatchUnification {
                expected: Identifier::from(&type_a.to_string()),
                found: Identifier::from(&type_b.to_string()),
            }),
        }
    }

    fn unify_generic_with_concrete(
        &mut self,
        symbol_table: &mut SymbolTable,
        generic_type: &mut Type,
        concrete_type: &Type,
    ) -> Result<(), SemanticErrorKind> {
        match generic_type {
            Type::Generic { name, bound_opt } => {
                // check if the concrete type satisfies the bounds of the generic type
                if let Some(bound_path) = bound_opt {
                    let bound_trait = self.lookup_trait(&bound_path)?;

                    // check if the concrete type implements the required trait
                    if !self.type_satisfies_bound(concrete_type, &bound_trait) {
                        return Err(SemanticErrorKind::TypeBoundNotSatisfied {
                            generic_name: name.clone(),
                            expected_bound: bound_path.to_identifier(),
                            found_type: concrete_type.clone(),
                        });
                    }
                }

                // if bounds are satisfied, perform the substitution
                self.substitute_generic_with_concrete(symbol_table, name, concrete_type);
                Ok(())
            }

            _ => self.unify_types(symbol_table, concrete_type, generic_type),
        }
    }

    /// Add a trait implementation to the type table.
    fn add_trait_implementation(&mut self, concrete_type: TypePath, trait_impl: TraitImplDef) {
        self.type_table
            .entry(concrete_type)
            .or_insert_with(Vec::new)
            .push(trait_impl);
    }

    /// Lookup logic to find the trait definition in the current scope
    fn lookup_trait(&mut self, bound_path: &TypePath) -> Result<TraitDef, SemanticErrorKind> {
        if let Some(Symbol::Trait { trait_def, .. }) = self.lookup(bound_path) {
            Ok(trait_def.clone())
        } else {
            Err(SemanticErrorKind::UndefinedSymbol {
                name: bound_path.type_name.to_string(),
            })
        }
    }

    /// Replace all occurrences of `generic_name` with `concrete_type`.
    fn substitute_generic_with_concrete(
        &mut self,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        let scope_stack = &self.scope_stack;

        // iterate through the scope stack and substitute generics in all types.
        for scope in scope_stack.to_owned().iter_mut() {
            for symbol in scope.symbols.values_mut() {
                self.substitute_in_symbol(symbol, symbol_table, generic_name, concrete_type);
            }
        }
    }

    fn substitute_in_symbol(
        &mut self,
        symbol: &mut Symbol,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        // apply substitution to each symbol within the current scope by delegating to specific
        // substitution functions
        match symbol {
            Symbol::Variable { var_type, .. } => {
                self.substitute_in_type(var_type, symbol_table, generic_name, concrete_type);
            }
            Symbol::Struct { struct_def, .. } => {
                self.substitute_in_struct(struct_def, symbol_table, generic_name, concrete_type);
            }
            Symbol::TupleStruct {
                tuple_struct_def, ..
            } => {
                self.substitute_in_tuple_struct(
                    tuple_struct_def,
                    symbol_table,
                    generic_name,
                    concrete_type,
                );
            }
            Symbol::Enum { enum_def, .. } => {
                self.substitute_in_enum(enum_def, symbol_table, generic_name, concrete_type);
            }
            Symbol::Trait { trait_def, .. } => {
                self.substitute_in_trait(trait_def, symbol_table, generic_name, concrete_type)
            }
            Symbol::Alias {
                original_type_opt, ..
            } => {
                self.substitute_opt_type(
                    original_type_opt,
                    symbol_table,
                    generic_name,
                    concrete_type,
                );
            }
            Symbol::Constant { constant_type, .. } => {
                self.substitute_in_type(constant_type, symbol_table, generic_name, concrete_type);
            }
            Symbol::Function { function, .. } => {
                self.substitute_in_function(function, symbol_table, generic_name, concrete_type);
            }
            Symbol::Module { module, .. } => {
                self.substitute_in_module(module, symbol_table, generic_name, concrete_type)
            }
        }
    }

    fn substitute_in_type(
        &mut self,
        ty: &mut Type,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        // perform substitution for types
        // if we encounter a generic type param, replace it with the concrete type
        match ty {
            Type::Generic { name, .. } if name == generic_name => {
                *ty = concrete_type.clone();
            }
            Type::GroupedType(inner_type) => {
                self.substitute_in_type(inner_type, symbol_table, generic_name, concrete_type)
            }
            Type::Array { element_type, .. } => {
                self.substitute_in_type(element_type, symbol_table, generic_name, concrete_type);
            }
            Type::Tuple(element_types) => {
                for elem_type in element_types {
                    self.substitute_in_type(elem_type, symbol_table, generic_name, concrete_type);
                }
            }
            Type::FunctionPtr(ptr) => {
                if let Some(params) = ptr.params_opt.as_mut() {
                    for param in params {
                        match param {
                            FunctionOrMethodParam::FunctionParam(FunctionParam {
                                param_type,
                                ..
                            }) => self.substitute_in_type(
                                param_type,
                                symbol_table,
                                generic_name,
                                concrete_type,
                            ),
                            FunctionOrMethodParam::MethodParam(_) => (),
                        }
                    }
                }

                if let Some(ty) = ptr.return_type_opt.as_mut() {
                    self.substitute_in_type(ty, symbol_table, generic_name, concrete_type);
                }
            }
            Type::Reference { inner_type, .. } => {
                self.substitute_in_type(inner_type, symbol_table, generic_name, concrete_type);
            }
            Type::UserDefined(type_path) => {
                if let Some(sym) = symbol_table.to_owned().get_mut(type_path) {
                    match sym {
                        Symbol::Variable { var_type, .. } => self.substitute_in_type(
                            var_type,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                        Symbol::Struct { struct_def, .. } => {
                            self.substitute_in_struct(
                                struct_def,
                                symbol_table,
                                generic_name,
                                concrete_type,
                            );
                        }
                        Symbol::TupleStruct {
                            tuple_struct_def, ..
                        } => self.substitute_in_tuple_struct(
                            tuple_struct_def,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                        Symbol::Enum { enum_def, .. } => {
                            self.substitute_in_enum(
                                enum_def,
                                symbol_table,
                                generic_name,
                                concrete_type,
                            );
                        }
                        Symbol::Trait { trait_def, .. } => {
                            self.substitute_in_trait(
                                trait_def,
                                symbol_table,
                                generic_name,
                                concrete_type,
                            );
                        }
                        Symbol::Alias {
                            original_type_opt, ..
                        } => self.substitute_opt_type(
                            original_type_opt,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                        Symbol::Constant { constant_type, .. } => self.substitute_in_type(
                            constant_type,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                        Symbol::Function { function, .. } => self.substitute_in_function(
                            function,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                        Symbol::Module { module, .. } => self.substitute_in_module(
                            module,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                    }
                }
            }
            Type::SelfType(_) => {
                unify_self_type(ty, concrete_type.clone());
            }
            Type::InferredType { .. } => unify_inferred_type(ty, concrete_type.clone()),
            Type::Vec { element_type } => {
                self.substitute_in_type(element_type, symbol_table, generic_name, concrete_type);
            }
            Type::Mapping {
                key_type,
                value_type,
            } => {
                self.substitute_in_type(key_type, symbol_table, generic_name, concrete_type);
                self.substitute_in_type(value_type, symbol_table, generic_name, concrete_type);
            }
            Type::Option { inner_type } => {
                self.substitute_in_type(inner_type, symbol_table, generic_name, concrete_type);
            }
            Type::Result { ok_type, err_type } => {
                self.substitute_in_type(ok_type, symbol_table, generic_name, concrete_type);
                self.substitute_in_type(err_type, symbol_table, generic_name, concrete_type);
            }

            _ => {}
        }
    }

    fn substitute_in_struct(
        &mut self,
        struct_def: &mut StructDef,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        if let Some(fields) = struct_def.fields_opt.as_mut() {
            for StructDefField { field_type, .. } in fields {
                self.substitute_in_type(field_type, symbol_table, generic_name, concrete_type);
            }
        }
    }

    fn substitute_in_tuple_struct(
        &mut self,
        tuple_struct_def: &mut TupleStructDef,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        if let Some(fields) = tuple_struct_def.fields_opt.as_mut() {
            for TupleStructDefField { field_type, .. } in fields {
                self.substitute_in_type(field_type, symbol_table, generic_name, concrete_type);
            }
        }
    }

    fn substitute_in_enum(
        &mut self,
        enum_def: &mut EnumDef,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        for variant in enum_def.variants.iter_mut() {
            if let Some(ty) = variant.variant_type_opt.as_mut() {
                match ty {
                    EnumVariantType::Struct(EnumVariantStruct { struct_fields }) => {
                        for StructDefField { field_type, .. } in struct_fields {
                            self.substitute_in_type(
                                field_type,
                                symbol_table,
                                generic_name,
                                concrete_type,
                            );
                        }
                    }
                    EnumVariantType::TupleStruct(EnumVariantTupleStruct { element_types }, ..) => {
                        for ty in element_types {
                            self.substitute_in_type(ty, symbol_table, generic_name, concrete_type);
                        }
                    }
                }
            }
        }
    }

    fn substitute_in_trait(
        &mut self,
        trait_def: &mut TraitDef,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        if let Some(items) = trait_def.trait_items_opt.as_mut() {
            for item in items {
                match item {
                    TraitDefItem::AliasDecl(AliasDecl {
                        original_type_opt, ..
                    }) => {
                        self.substitute_opt_type(
                            original_type_opt,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        );
                    }
                    TraitDefItem::ConstantDecl(ConstantDecl { constant_type, .. }) => self
                        .substitute_in_type(
                            constant_type,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                    TraitDefItem::FunctionItem(function_item) => self.substitute_in_function(
                        function_item,
                        symbol_table,
                        generic_name,
                        concrete_type,
                    ),
                }
            }
        }
    }

    fn substitute_in_function(
        &mut self,
        function: &mut FunctionItem,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        if let Some(params) = function.params_opt.as_mut() {
            for param in params {
                self.substitute_in_type(
                    &mut param.param_type(),
                    symbol_table,
                    generic_name,
                    concrete_type,
                );
            }
        }

        if let Some(return_type) = function.return_type_opt.as_mut() {
            self.substitute_in_type(return_type, symbol_table, generic_name, concrete_type);
        }
    }

    fn substitute_in_module(
        &mut self,
        module: &mut ModuleItem,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        if let Some(items) = module.items_opt.as_mut() {
            for item in items {
                match item {
                    Item::AliasDecl(AliasDecl {
                        original_type_opt, ..
                    }) => self.substitute_opt_type(
                        original_type_opt,
                        symbol_table,
                        generic_name,
                        concrete_type,
                    ),
                    Item::ConstantDecl(ConstantDecl { constant_type, .. }) => self
                        .substitute_in_type(
                            constant_type,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        ),
                    Item::StaticVarDecl(StaticVarDecl { var_type, .. }) => {
                        self.substitute_in_type(var_type, symbol_table, generic_name, concrete_type)
                    }
                    Item::ModuleItem(module) => {
                        self.substitute_in_module(module, symbol_table, generic_name, concrete_type)
                    }
                    Item::TraitDef(trait_def) => self.substitute_in_trait(
                        trait_def,
                        symbol_table,
                        generic_name,
                        concrete_type,
                    ),
                    Item::EnumDef(enum_def) => {
                        self.substitute_in_enum(
                            enum_def,
                            symbol_table,
                            generic_name,
                            concrete_type,
                        );
                    }
                    Item::StructDef(struct_def) => self.substitute_in_struct(
                        struct_def,
                        symbol_table,
                        generic_name,
                        concrete_type,
                    ),
                    Item::TupleStructDef(tuple_struct_def) => self.substitute_in_tuple_struct(
                        tuple_struct_def,
                        symbol_table,
                        generic_name,
                        concrete_type,
                    ),
                    Item::FunctionItem(function) => self.substitute_in_function(
                        function,
                        symbol_table,
                        generic_name,
                        concrete_type,
                    ),
                    Item::InherentImplDef(InherentImplDef {
                        associated_items_opt,
                        ..
                    }) => {
                        if let Some(assoc_items) = associated_items_opt.as_mut() {
                            for item in assoc_items {
                                match item {
                                    InherentImplItem::ConstantDecl(ConstantDecl {
                                        constant_type,
                                        ..
                                    }) => self.substitute_in_type(
                                        constant_type,
                                        symbol_table,
                                        generic_name,
                                        concrete_type,
                                    ),
                                    InherentImplItem::FunctionItem(function) => self
                                        .substitute_in_function(
                                            function,
                                            symbol_table,
                                            generic_name,
                                            concrete_type,
                                        ),
                                }
                            }
                        }
                    }
                    Item::TraitImplDef(TraitImplDef {
                        associated_items_opt,
                        ..
                    }) => {
                        if let Some(assoc_items) = associated_items_opt.as_mut() {
                            for item in assoc_items {
                                match item {
                                    TraitImplItem::AliasDecl(AliasDecl {
                                        original_type_opt,
                                        ..
                                    }) => self.substitute_opt_type(
                                        original_type_opt,
                                        symbol_table,
                                        generic_name,
                                        concrete_type,
                                    ),
                                    TraitImplItem::ConstantDecl(ConstantDecl {
                                        constant_type,
                                        ..
                                    }) => self.substitute_in_type(
                                        constant_type,
                                        symbol_table,
                                        generic_name,
                                        concrete_type,
                                    ),
                                    TraitImplItem::FunctionItem(function) => self
                                        .substitute_in_function(
                                            function,
                                            symbol_table,
                                            generic_name,
                                            concrete_type,
                                        ),
                                }
                            }
                        }
                    }
                    _ => (),
                }
            }
        }
    }

    fn substitute_opt_type(
        &mut self,
        original_type_opt: &mut Option<Type>,
        symbol_table: &mut SymbolTable,
        generic_name: &Identifier,
        concrete_type: &Type,
    ) {
        if let Some(ty) = original_type_opt {
            self.substitute_in_type(ty, symbol_table, generic_name, concrete_type);
        }
    }

    /// Checks if a given type satisfies a specific trait bound.
    fn type_satisfies_bound(&self, concrete_type: &Type, bound_trait: &TraitDef) -> bool {
        // retrieve all the trait implementations for the concrete type from the symbol table
        // or registry
        let trait_implementations = self.get_trait_implementations(concrete_type);

        // check if any of the implementations match the required trait
        for trait_impl in trait_implementations.iter() {
            if self.trait_matches(trait_impl, bound_trait) {
                return true;
            }
        }

        // if no matching trait implementations were found, the bound is not satisfied
        false
    }

    fn get_trait_implementations(&self, concrete_type: &Type) -> Vec<TraitImplDef> {
        // convert concrete type to its `TypePath` representation
        if let Some(type_path) = resolve_type_path(concrete_type) {
            // look up the trait implementations in the type table
            if let Some(trait_impls) = self.type_table.get(&type_path) {
                return trait_impls.clone();
            }
        }

        // if no implementations are found, return an empty vector
        Vec::new()
    }

    /// Check if the trait implementation matches the required trait.
    fn trait_matches(&self, trait_impl: &TraitImplDef, bound_trait: &TraitDef) -> bool {
        // TODO: check the path and the associated generic parameters
        // TODO: compare full paths and resolve them properly.
        trait_impl.implemented_trait_path.type_name == bound_trait.trait_name
    }

    fn log_error(&mut self, error_kind: SemanticErrorKind, span: &Span) {
        let error = CompilerError::new(error_kind, span.start(), &span.input());

        self.logger.error(&error.to_string());
        self.errors.push(error);
    }
}

/// Helper function to resolve `Type` to `TypePath`.
fn resolve_type_path(ty: &Type) -> Option<TypePath> {
    match ty {
        Type::UserDefined(type_path) => Some(type_path.clone()),
        _ => None,
    }
}

fn unify_inferred_type(ty: &mut Type, concrete_type: Type) {
    if *ty == Type::inferred_type("_") {
        if concrete_type != Type::inferred_type("_") {
            *ty = concrete_type;
        }
    }
}

/// Attempt to unify the types of two `Result` types, specifically between an inferred type
/// and a context type. This function is used to ensure that the `Ok` and `Err` variants of
/// an inferred `Result` type match the expected types defined in the context.
fn unify_result_types(ty: &mut Type, context_type: &Type) -> Result<(), SemanticErrorKind> {
    let ty_clone = ty.clone();

    match (ty, context_type) {
        (
            Type::Result {
                ok_type: inf_ok,
                err_type: inf_err,
            },
            Type::Result {
                ok_type: ctx_ok,
                err_type: ctx_err,
            },
        ) => {
            if **inf_ok == Type::inferred_type("_") {
                *inf_ok = ctx_ok.clone();
            } else if **ctx_ok != Type::inferred_type("_") && **inf_ok != **ctx_ok {
                return Err(SemanticErrorKind::TypeMismatchResultExpr {
                    variant: Keyword::Ok,
                    expected: *ctx_ok.clone(),
                    found: *(*inf_ok).clone(),
                });
            }

            if **inf_err == Type::inferred_type("_") {
                *inf_err = ctx_err.clone();
            } else if **ctx_err != Type::inferred_type("_") && **inf_err != **ctx_err {
                return Err(SemanticErrorKind::TypeMismatchResultExpr {
                    variant: Keyword::Err,
                    expected: *ctx_err.clone(),
                    found: *(*inf_err).clone(),
                });
            }
            Ok(())
        }
        _ => Err(SemanticErrorKind::UnexpectedType {
            expected: context_type.to_string(),
            found: ty_clone,
        }),
    }
}

fn unify_self_type(ty: &mut Type, object_type: Type) {
    if *ty == Type::SelfType(SelfType) {
        if object_type != Type::SelfType(SelfType) && object_type != Type::inferred_type("_") {
            *ty = object_type;
        }
    }
}
